{
	"about": "https://jvndb.jvn.jp/ja/contents/2023/JVNDB-2023-008489.html",
	"title": "pega の synchronization engine におけるデータの信頼性についての不十分な検証に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2023/JVNDB-2023-008489.html",
	"description": "pega の synchronization engine には、データの信頼性についての不十分な検証に関する脆弱性が存在します。",
	"identifier": "JVNDB-2023-008489",
	"references": [
		{
			"text": "https://www.cve.org/CVERecord?id=CVE-2023-26467",
			"source": "CVE",
			"id": "CVE-2023-26467"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2023-26467",
			"source": "NVD",
			"id": "CVE-2023-26467"
		},
		{
			"text": "https://support.pega.com/support-doc/pega-security-advisory-b23-robotics-and-workforce-intelligence-local-privilege",
			"source": "関連文書",
			"id": "support.pega.com (pega-security-advisory-b23-robotics-and-workforce-intelligence-local-privilege)"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/345.html",
			"id": "CWE-345",
			"title": "データの信頼性についての不十分な検証(CWE-345)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:pega:synchronization_engine",
			"version": "2.2",
			"vendor": "pega",
			"product": "synchronization engine"
		}
	],
	"cvss": [
		{
			"version": "3.0",
			"score": "5.4",
			"type": "Base",
			"severity": "Medium",
			"vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:N"
		}
	],
	"date": "2023-12-01T14:21+09:00",
	"issued": "2023-12-01T14:21+09:00",
	"modified": "2023-12-01T14:21+09:00"
}
