{
	"about": "https://jvndb.jvn.jp/ja/contents/2023/JVNDB-2023-010061.html",
	"title": "Socket.IO の Node.js 用 engine.io におけるキャッチされない例外に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2023/JVNDB-2023-010061.html",
	"description": "Socket.IO の Node.js 用 engine.io には、キャッチされない例外に関する脆弱性が存在します。",
	"identifier": "JVNDB-2023-010061",
	"references": [
		{
			"text": "https://www.cve.org/CVERecord?id=CVE-2023-31125",
			"source": "CVE",
			"id": "CVE-2023-31125"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2023-31125",
			"source": "NVD",
			"id": "CVE-2023-31125"
		},
		{
			"text": "https://github.com/socketio/engine.io/commit/fc480b4f305e16fe5972cf337d055e598372dc44",
			"source": "関連文書",
			"id": "github.com (fc480b4f305e16fe5972cf337d055e598372dc44)"
		},
		{
			"text": "https://github.com/socketio/engine.io/releases/tag/6.4.2",
			"source": "関連文書",
			"id": "github.com (6.4.2)"
		},
		{
			"text": "https://github.com/socketio/engine.io/security/advisories/GHSA-q9mw-68c2-j6m5",
			"source": "関連文書",
			"id": "github.com (GHSA-q9mw-68c2-j6m5)"
		},
		{
			"text": "https://security.netapp.com/advisory/ntap-20230622-0002/",
			"source": "関連文書",
			"id": "security.netapp.com (ntap-20230622-0002)"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/248.html",
			"id": "CWE-248",
			"title": "キャッチされない例外(CWE-248)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:socket:engine.io",
			"version": "2.2",
			"vendor": "Socket.IO",
			"product": "engine.io"
		}
	],
	"cvss": [
		{
			"version": "3.0",
			"score": "6.5",
			"type": "Base",
			"severity": "Medium",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"date": "2023-12-07T16:24+09:00",
	"issued": "2023-12-07T16:24+09:00",
	"modified": "2023-12-07T16:24+09:00"
}
