{
	"about": "https://jvndb.jvn.jp/ja/contents/2019/JVNDB-2019-010225.html",
	"title": "Unbound におけるバッファエラーの脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2019/JVNDB-2019-010225.html",
	"description": "Unbound には、バッファエラーの脆弱性が存在します。",
	"identifier": "JVNDB-2019-010225",
	"references": [
		{
			"text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16866",
			"source": "CVE",
			"id": "CVE-2019-16866"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2019-16866",
			"source": "NVD",
			"id": "CVE-2019-16866"
		},
		{
			"text": "https://jvndb.jvn.jp/ja/cwe/CWE-119.html",
			"id": "CWE-119",
			"title": "バッファエラー(CWE-119)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:nlnet_labs:unbound",
			"version": "2.2",
			"vendor": "Stichting NLnet Labs",
			"product": "Unbound"
		},
		{
			"text": "cpe:/o:canonical:ubuntu_linux",
			"version": "2.2",
			"vendor": "Canonical",
			"product": "Ubuntu"
		}
	],
	"cvss": [
		{
			"version": "2.0",
			"score": "5.0",
			"type": "Base",
			"severity": "Medium",
			"vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
		},
		{
			"version": "3.0",
			"score": "7.5",
			"type": "Base",
			"severity": "High",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"date": "2019-10-09T17:36+09:00",
	"issued": "2019-10-09T17:36+09:00",
	"modified": "2019-10-09T17:36+09:00"
}
