{
	"about": "https://jvndb.jvn.jp/ja/contents/2019/JVNDB-2019-011546.html",
	"title": "python-docutils における誤った領域へのリソースの漏えいに関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2019/JVNDB-2019-011546.html",
	"description": "python-docutils には、誤った領域へのリソースの漏えいに関する脆弱性が存在します。",
	"identifier": "JVNDB-2019-011546",
	"references": [
		{
			"text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-5042",
			"source": "CVE",
			"id": "CVE-2009-5042"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2009-5042",
			"source": "NVD",
			"id": "CVE-2009-5042"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/668.html",
			"id": "CWE-668",
			"title": "誤った領域へのリソースの漏えい(CWE-668)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:python-docutils_project:python-docutils",
			"version": "2.2",
			"vendor": "python-docutils project",
			"product": "Docutils"
		},
		{
			"text": "cpe:/o:debian:debian_linux",
			"version": "2.2",
			"vendor": "Debian",
			"product": "Debian GNU/Linux"
		}
	],
	"cvss": [
		{
			"version": "2.0",
			"score": "6.4",
			"type": "Base",
			"severity": "Medium",
			"vector": "AV:N/AC:L/Au:N/C:P/I:P/A:N"
		},
		{
			"version": "3.0",
			"score": "9.1",
			"type": "Base",
			"severity": "Critical",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N"
		}
	],
	"date": "2019-11-12T17:21+09:00",
	"issued": "2019-11-12T17:21+09:00",
	"modified": "2019-11-12T17:21+09:00"
}
