{
  "about": "https://jvndb.jvn.jp/ja/contents/2019/JVNDB-2019-010570.html",
  "title": "Zoho ManageEngine DataSecurity Plus における外部からアクセス可能なファイルまたはディレクトリに関する脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2019/JVNDB-2019-010570.html",
  "description": "Zoho ManageEngine DataSecurity Plus には、外部からアクセス可能なファイルまたはディレクトリに関する脆弱性が存在します。",
  "identifier": "JVNDB-2019-010570",
  "references": [
    {
      "text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-17112",
      "source": "CVE",
      "id": "CVE-2019-17112"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2019-17112",
      "source": "NVD",
      "id": "CVE-2019-17112"
    },
    {
      "text": "https://excellium-services.com/cert-xlm-advisory/cve-2019-17112/",
      "source": "関連文書",
      "id": "CVE-2019-17112"
    },
    {
      "text": "https://cwe.mitre.org/data/definitions/552.html",
      "id": "CWE-552",
      "title": "外部からアクセス可能なファイルまたはディレクトリ(CWE-552)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:zohocorp:manageengine_datasecurity_plus",
      "version": "2.2",
      "vendor": "Zoho Corporation",
      "product": "ManageEngine DataSecurity Plus"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "4.0",
      "type": "Base",
      "severity": "Medium",
      "vector": "AV:N/AC:L/Au:S/C:P/I:N/A:N"
    },
    {
      "version": "3.0",
      "score": "4.3",
      "type": "Base",
      "severity": "Medium",
      "vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N"
    }
  ],
  "date": "2019-10-17T12:07+09:00",
  "issued": "2019-10-17T12:07+09:00",
  "modified": "2019-10-17T12:07+09:00"
}
