{
  "about": "https://jvndb.jvn.jp/ja/contents/2015/JVNDB-2015-004456.html",
  "title": "Django の contrib.sessions.backends.base.SessionBase.flush 関数および cache_db.SessionStore.flush 関数におけるサービス運用妨害 (DoS) の脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2015/JVNDB-2015-004456.html",
  "description": "Django の (1) contrib.sessions.backends.base.SessionBase.flush 関数および (2) cache_db.SessionStore.flush 関数は、特定の状況で空のセッションを作成するため、サービス運用妨害 (セッションストアの消費) 状態にされる脆弱性が存在します。",
  "identifier": "JVNDB-2015-004456",
  "references": [
    {
      "text": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-5964",
      "source": "CVE",
      "id": "CVE-2015-5964"
    },
    {
      "text": "http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-5964",
      "source": "NVD",
      "id": "CVE-2015-5964"
    },
    {
      "text": "https://jvndb.jvn.jp/ja/cwe/CWE-399.html",
      "id": "CWE-399",
      "title": "リソース管理の問題(CWE-399)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:djangoproject:django",
      "version": "2.2",
      "vendor": "Django Software Foundation",
      "product": "Django"
    },
    {
      "text": "cpe:/o:canonical:ubuntu",
      "version": "2.2",
      "vendor": "Canonical",
      "product": "Ubuntu"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "5.0",
      "type": "Base",
      "severity": "Medium",
      "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
    }
  ],
  "date": "2015-11-06T15:43+09:00",
  "issued": "2015-08-27T16:28+09:00",
  "modified": "2015-11-06T15:43+09:00"
}
