{
  "about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-002597.html",
  "title": "Django における SQL インジェクションの脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-002597.html",
  "description": "Django には、SQL インジェクションの脆弱性が存在します。",
  "identifier": "JVNDB-2020-002597",
  "references": [
    {
      "text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-9402",
      "source": "CVE",
      "id": "CVE-2020-9402"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2020-9402",
      "source": "NVD",
      "id": "CVE-2020-9402"
    },
    {
      "text": "https://jvndb.jvn.jp/ja/cwe/CWE-89.html",
      "id": "CWE-89",
      "title": "SQLインジェクション(CWE-89)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:djangoproject:django",
      "version": "2.2",
      "vendor": "Django Software Foundation",
      "product": "Django"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "7.5",
      "type": "Base",
      "severity": "High",
      "vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    {
      "version": "3.0",
      "score": "9.8",
      "type": "Base",
      "severity": "Critical",
      "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "date": "2020-03-19T18:10+09:00",
  "issued": "2020-03-19T18:10+09:00",
  "modified": "2020-03-19T18:10+09:00"
}
