{
	"about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-014803.html",
	"title": "Odoo Community および Enterprise における脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-014803.html",
	"description": "Odoo Community および Enterprise には、不特定の脆弱性が存在します。",
	"identifier": "JVNDB-2020-014803",
	"references": [
		{
			"text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-29396",
			"source": "CVE",
			"id": "CVE-2020-29396"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2020-29396",
			"source": "NVD",
			"id": "CVE-2020-29396"
		},
		{
			"text": "https://www.ipa.go.jp/security/vuln/scap/cwe.html",
			"id": "CWE-noinfo",
			"title": "情報不足(CWE-noinfo)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:odoo:odoo",
			"version": "2.2",
			"vendor": "Odoo",
			"product": "Odoo"
		}
	],
	"cvss": [
		{
			"version": "2.0",
			"score": "6.5",
			"type": "Base",
			"severity": "Medium",
			"vector": "AV:N/AC:L/Au:S/C:P/I:P/A:P"
		},
		{
			"version": "3.0",
			"score": "8.8",
			"type": "Base",
			"severity": "High",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"date": "2021-08-31T18:04+09:00",
	"issued": "2021-08-31T18:04+09:00",
	"modified": "2021-08-31T18:04+09:00"
}
