{
	"about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-015718.html",
	"title": "jinja2 におけるリソースの枯渇に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-015718.html",
	"description": "jinja2 には、リソースの枯渇に関する脆弱性が存在します。",
	"identifier": "JVNDB-2020-015718",
	"references": [
		{
			"text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28493",
			"source": "CVE",
			"id": "CVE-2020-28493"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2020-28493",
			"source": "NVD",
			"id": "CVE-2020-28493"
		},
		{
			"text": "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994",
			"source": "関連文書",
			"id": "SNYK-PYTHON-JINJA2-1012994 (Regular Expression Denial of Service (ReDoS)Affecting jinja2 package, versions [,2.11.3))"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/400.html",
			"id": "CWE-400",
			"title": "リソースの枯渇(CWE-400)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:palletsprojects:jinja",
			"version": "2.2",
			"vendor": "Pallets project",
			"product": "Jinja"
		},
		{
			"text": "cpe:/o:fedoraproject:fedora",
			"version": "2.2",
			"vendor": "Fedora Project",
			"product": "Fedora"
		}
	],
	"cvss": [
		{
			"version": "2.0",
			"score": "5.0",
			"type": "Base",
			"severity": "Medium",
			"vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
		},
		{
			"version": "3.0",
			"score": "5.3",
			"type": "Base",
			"severity": "Medium",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
		}
	],
	"date": "2021-10-12T13:51+09:00",
	"issued": "2021-10-12T13:51+09:00",
	"modified": "2021-10-12T13:51+09:00"
}
