{
  "about": "https://jvndb.jvn.jp/ja/contents/2022/JVNDB-2022-020662.html",
  "title": "Python Software Foundation の Python Pillow におけるリソースの枯渇に関する脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2022/JVNDB-2022-020662.html",
  "description": "Python Software Foundation の Python Pillow には、リソースの枯渇に関する脆弱性が存在します。",
  "identifier": "JVNDB-2022-020662",
  "references": [
    {
      "text": "https://www.cve.org/CVERecord?id=CVE-2022-45199",
      "source": "CVE",
      "id": "CVE-2022-45199"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2022-45199",
      "source": "NVD",
      "id": "CVE-2022-45199"
    },
    {
      "text": "https://bugs.gentoo.org/878769",
      "source": "関連文書",
      "id": "bugs.gentoo.org (878769)"
    },
    {
      "text": "https://github.com/python-pillow/Pillow/commit/2444cddab2f83f28687c7c20871574acbb6dbcf3",
      "source": "関連文書",
      "id": "github.com (2444cddab2f83f28687c7c20871574acbb6dbcf3)"
    },
    {
      "text": "https://github.com/python-pillow/Pillow/pull/6700",
      "source": "関連文書",
      "id": "github.com (pull/6700)"
    },
    {
      "text": "https://github.com/python-pillow/Pillow/releases/tag/9.3.0",
      "source": "関連文書",
      "id": "github.com (9.3.0)"
    },
    {
      "text": "https://security.gentoo.org/glsa/202211-10",
      "source": "関連文書",
      "id": "security.gentoo.org (202211-10)"
    },
    {
      "text": "https://cwe.mitre.org/data/definitions/400.html",
      "id": "CWE-400",
      "title": "リソースの枯渇(CWE-400)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:python:pillow",
      "version": "2.2",
      "vendor": "Python Software Foundation",
      "product": "Python Pillow"
    }
  ],
  "cvss": [
    {
      "version": "3.0",
      "score": "7.5",
      "type": "Base",
      "severity": "High",
      "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "date": "2023-11-06T17:05+09:00",
  "issued": "2023-11-06T17:05+09:00",
  "modified": "2023-11-06T17:05+09:00"
}
