{
	"about": "https://jvndb.jvn.jp/ja/contents/2022/JVNDB-2022-013509.html",
	"title": "openhwgroup の cva6 における例外的な状態の処理に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2022/JVNDB-2022-013509.html",
	"description": "openhwgroup の cva6 には、例外的な状態の処理に関する脆弱性が存在します。",
	"identifier": "JVNDB-2022-013509",
	"references": [
		{
			"text": "https://www.cve.org/CVERecord?id=CVE-2022-34633",
			"source": "CVE",
			"id": "CVE-2022-34633"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2022-34633",
			"source": "NVD",
			"id": "CVE-2022-34633"
		},
		{
			"text": "https://github.com/openhwgroup/cva6/issues/876",
			"source": "関連文書",
			"id": "github.com (issues/876)"
		},
		{
			"text": "https://github.com/openhwgroup/cva6/pull/921",
			"source": "関連文書",
			"id": "github.com (pull/921)"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/755.html",
			"id": "CWE-755",
			"title": "例外的な状態における不適切な処理(CWE-755)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:openhwgroup:cva6",
			"version": "2.2",
			"vendor": "openhwgroup",
			"product": "cva6"
		}
	],
	"cvss": [
		{
			"version": "3.0",
			"score": "5.5",
			"type": "Base",
			"severity": "Medium",
			"vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"date": "2023-09-08T17:27+09:00",
	"issued": "2023-09-08T17:27+09:00",
	"modified": "2023-09-08T17:27+09:00"
}
