{
	"about": "https://jvndb.jvn.jp/ja/contents/2022/JVNDB-2022-023104.html",
	"title": "daloradius における認証の欠如に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2022/JVNDB-2022-023104.html",
	"description": "daloradius には、認証の欠如に関する脆弱性が存在します。",
	"identifier": "JVNDB-2022-023104",
	"references": [
		{
			"text": "https://www.cve.org/CVERecord?id=CVE-2022-4366",
			"source": "CVE",
			"id": "CVE-2022-4366"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2022-4366",
			"source": "NVD",
			"id": "CVE-2022-4366"
		},
		{
			"text": "https://github.com/lirantal/daloradius/commit/3d11f375a76ddb3741200296e15f81d82dfb80ce",
			"source": "関連文書",
			"id": "github.com (3d11f375a76ddb3741200296e15f81d82dfb80ce)"
		},
		{
			"text": "https://huntr.dev/bounties/f225d69a-d971-410d-a8f9-b0026143aed8",
			"source": "関連文書",
			"id": "huntr.dev (f225d69a-d971-410d-a8f9-b0026143aed8)"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/862.html",
			"id": "CWE-862",
			"title": "認証の欠如(CWE-862)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:daloradius:daloradius",
			"version": "2.2",
			"vendor": "daloradius",
			"product": "daloradius"
		}
	],
	"cvss": [
		{
			"version": "3.0",
			"score": "7.5",
			"type": "Base",
			"severity": "High",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
		}
	],
	"date": "2023-11-27T12:03+09:00",
	"issued": "2023-11-27T12:03+09:00",
	"modified": "2023-11-27T12:03+09:00"
}
