{
  "about": "https://jvndb.jvn.jp/ja/contents/2021/JVNDB-2021-013331.html",
  "title": "python-tuf におけるパストラバーサルの脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2021/JVNDB-2021-013331.html",
  "description": "python-tuf には、パストラバーサルの脆弱性が存在します。",
  "identifier": "JVNDB-2021-013331",
  "references": [
    {
      "text": "https://www.cve.org/CVERecord?id=CVE-2021-41131",
      "source": "CVE",
      "id": "CVE-2021-41131"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2021-41131",
      "source": "NVD",
      "id": "CVE-2021-41131"
    },
    {
      "text": "https://jvndb.jvn.jp/ja/cwe/CWE-22.html",
      "id": "CWE-22",
      "title": "パス・トラバーサル(CWE-22)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:linuxfoundation:the_update_framework",
      "version": "2.2",
      "vendor": "Linux Foundation",
      "product": "The Update Framework"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "8.8",
      "type": "Base",
      "severity": "High",
      "vector": "AV:N/AC:M/Au:N/C:N/I:C/A:C"
    },
    {
      "version": "3.0",
      "score": "8.7",
      "type": "Base",
      "severity": "High",
      "vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:H"
    }
  ],
  "date": "2022-09-08T15:04+09:00",
  "issued": "2022-09-08T15:04+09:00",
  "modified": "2022-09-08T15:04+09:00"
}
